apiVersion: apps/v1
kind: Deployment
  name: nginx
spec:
  template:
    spec:
      containers:
      - name: nginx
        ...
        volumeMounts:
        - mountPath: /var/log
          name: nginx-ingress-pvc
      volumes:
      - name: nginx-ingress-pvc
        persistentVolumeClaim:
          claimName: nginx-ingress-pvc